정렬/k번째_수.js
[K번째 수](https://school.programmers.co.kr/learn/courses/30/lessons/42748)
반복문 안에 slice, sort 메소드 활용
```
function solution(array, commands) {
let answer = [];
let command = [];
for(i = 0; i < commands.length ; i++) {
command = commands[i]
answer.push(array.slice(command[0]-1,command[1]).sort((a, b) => a - b)[command[2]-1]);
}
return answer;
}
```
=> [김혜중] 프로그래머스 - 정렬

정렬/k번째_수.js
function solution(array, commands) {
var answer = [];
var commands = [[2, 5, 3], [4, 4, 1], [1, 7, 3]];
var array = [1, 5, 2, 6, 3, 7, 4];
for (let i = 0; i < commands.length; i++) {
let slice = (array.slice(commands[i][0]-1, commands[i][1])).sort((a, b) => a - b);
answer.push(slice[commands[i][2]-1]);
};
return answer;
}
=> [백민서] 정렬-k번째수

정렬/[백준] 세수정렬.js
시간이 부족해서 버블정렬, 삽입정렬, 선택정렬 세 가지 봤고 그중에서 버블정렬로 구현했습니다.
백준에서 입력 받는 것과 제출하는 방법 찾아보다가 시간 없어서 일단 PR 보냈어요...🥲
`j`번째 값과 `j + 1`번째 값을 활용해서 마지막 인덱스는 확인할 필요가 없어 배열의 `length`값에 `-1`한 값까지 반복문이 돌게 했습니다.
`i`번째 회전을 하면 최소 `i`개의 값은 정렬이 되어 있다는 생각에서 내부 반복문에서 `-i`을 추가했습니다.
```javascript
// https://www.acmicpc.net/problem/2752
function solution(arr) {
for (let i = 0; i < arr.length; i++) {
let change = null;
for (let j = 0; j < arr.length - 1 - i; j++) {
if (arr[j] > arr[j + 1]) {
change = arr[j];
arr[j] = arr[j + 1];
arr[j + 1] = change;
}
}
if (!change) {
break;
}
}
return arr;
}
console.log(solution([3, 1, 2, 6, 4, 5]));
```
=> [정봉찬][백준] 세수정렬

정렬/가장 큰수(메모리 용량 오류).js, 정렬/가장 큰수(성공).js
순열을 이용해서 result 배열에 나올 수 있는 수들을 할당했고
그 중에서 가장 큰 수를 출력했다. 하지만 메모리 용량 오류가 발생하였다.
=> [심민보] 가장 큰 수

스택,큐/[프로그래머스] 올바른 괄호.js
코드잇 커리큘럼 진행하느라 시간이 너무 부족하네요...
처음에 '닫는 괄호'로 시작하면 종료하고 '여는 괄호'와 '닫는 괄호'의 수가 같으면 통과하는 단순한 생각으로 접근했습니다.
시간 여유가 있다면 풀지 않았을까 싶습니다...!
```javascript
function solution(s) {
var answer = true;
const open = [];
const close = [];
for (let i = 0; i < s.length; i++) {
const bracket = s[i];
if (i === 0 && bracket === ')') {
answer = false;
break;
}
if (bracket === '(') {
open.push(bracket);
continue;
}
close.push(bracket);
}
if (open.length !== close.length) answer = false;
return answer;
}
```
=> [정봉찬] 프로그래머스 - 올바른 괄호

스택,큐/프로그래머스_올바른_괄호.js
```
function solution(s){
let answer = true
//괄호 갯수(스택의 크기)
let parenthesis = 0;
for(let i = 0; i < s.length; i++) {
if(s[i]==='(') {
parenthesis++
} else {
parenthesis--
}
//parenthesis가 음수가 나오면 바로 false로 리턴한다.
if(parenthesis <0) {
return answer = false
}
}
//parenthesis가 0이 아니면 false
if(parenthesis !== 0) {
return answer = false
} 
return answer
}
```
=> [김혜중]프로그래머스_올바른 괄호

해시/폰켓몬.js
Reverts smb0123/Coding-test-Study#22
=> Revert "[심민보] 폰켓몬"

해시/폰켓몬.js
Reverts smb0123/Coding-test-Study#24
=> Revert "Revert "[심민보] 폰켓몬""

Kakao Blind/[프로그래머스] 개인정보 수집 유효기간.js
날짜 계산을 보고 년, 월, 일을 일로 계산 후 비교하면 좋겠다는 생각으로 접근했습니다.
```javascript
function solution(today, terms, privacies) {
var answer = [];
const todayDay = dateToDay(today);
const termTypeObj = {};
terms.forEach((term) => {
const [type, month] = term.split(' ');
termTypeObj[type] = monthToDay(month);
});
privacies.forEach((privacy, index) => {
const [date, type] = privacy.split(' ');
const privacyDay = dateToDay(date);
const remainDay = termTypeObj[type];
if (todayDay - privacyDay >= remainDay) {
answer.push(index + 1);
}
});
return answer;
}
function dateToDay(date) {
const [year, month, day] = date.split('.');
const resultDay = yearToDay(year) + monthToDay(month) + Number(day);
return resultDay;
}
function yearToDay(year) {
const day = Number(year) * 12 * 28;
return day;
}
function monthToDay(month) …
```
=> [정봉찬]프로그래머스 - 개인정보 수집 유효기간

2023KAKAO/개인정보_수집_유효기간.js
```javascript
function solution(today, terms, privacies) {
const todayDate = new Date(today);
const termObj = {};
terms.forEach((term) => {
const [type, period] = term.split(" ");
termObj[type] = parseInt(period, 10);
});
const deleteList = [];
privacies.forEach((privacy, index) => {
const [date, term] = privacy.split(" ");
const expireMonth = termObj[term];
const collectionDate = new Date(date);
const expireDay = new Date(
collectionDate.setMonth(collectionDate.getMonth() + expireMonth)
);
if (expireDay <= todayDate) {
deleteList.push(index + 1);
}
});
return deleteList;
}
```
=> [김혜중]프로그래머스 카카오 개인정보 수집 유효기간

해시/[프로그래머스] 완주하지 못한 선수.js
Map에 참가자를 + 1씩 더해주고 완주자를 - 1씩 빼주어서 계산했습니다.
1차 풀이 후 다른 사람 풀이를 참고했고 2차 풀이 했습니다.
사실 1차와 2차는 시간 복잡도가 같기 때문에 성능에는 차이가 없었습니다.
```javascript
function solution(participant, completion) {
var answer = '';
const map = new Map();
participant.forEach((item) => {
map.set(item, (map.get(item) || 0) + 1);
});
completion.forEach((item) => {
map.set(item, (map.get(item) || 0) - 1);
});
for (const [key, value] of map) {
if (value >= 1) {
answer = key;
break;
}
}
return answer;
}
```
```javascript
function solution(participant, completion) {
var answer = '';
const map = new Map();
for (let i = 0; i < participant.length; i++) {
const p = participant[i];
const c = completion[i];
map.set(p, (map.get(p) || 0) + 1);
map.set(c, (map.get(c) || 0) - 1);
}
for (const [key, value] of map) {
if (value > 0) {
answer = …
```
=> [정봉찬] 프로그래머스 - 완주하지 못한 선수

해시/완주하지 못한 선수.js
```javascript
function solution(participant, completion) {
const map = new Map();
for (const name of completion) {
map.set(name, (map.get(name) || 0) + 1);
}
for (const name of participant) {
const count = map.get(name);
if (count === undefined || count === 0) {
return name;
} else {
map.set(name, count - 1);
}
}
}
```
Map 객체를 만들고 completion에 키: 값 형태로 저장하였고 participant의 원소들을 하나씩 검사해서 get메소드를 이용해서 해당 값이 0이나 undefined가 아니면 set 메서드를 이용해서 1을 빼주었고 맞으면 return 했다.
=> [심민보] 완주하지 못한 선수

해시/완주하지못한선수.js
```javascript
function solution(participant, completion) {
const participantMap = new Map();
for (const name of participant) {
participantMap.set(name, (participantMap.get(name) || 0) + 1);
}
for (const name of completion) {
participantMap.set(name, participantMap.get(name) - 1);
}
let answer = null;
participantMap.forEach((count, name) => {
if (count > 0) {
answer = name;
return;
}
});
return answer;
}
```
=> [김혜중]프로그래머스 완주하지 못한 선수

해시/[프로그래머스] 전화번호 목록.js
처음에 중첩 반복문을 통해서 풀었는데 실패하고 해시랑 어떻게 관련지어 풀어야 할지 고민하다가 풀이를 봤습니다.
```js
function solution(phone_book) {
var answer = true;
outer: for (let i = 0; i < phone_book.length; i++) {
const phone = phone_book[i];
for (let j = i + 1; j < phone_book.length; j++) {
if (phone_book[j].indexOf(phone) === 0) {
answer = false;
break outer;
}
}
}
return answer;
}
```
```js
function solution(phone_book) {
var answer = true;
phone_book.sort();
answer = !phone_book.some((phone, index) =>
phone_book[index + 1]?.startsWith(phone)
);
return answer;
}
```
=> [정봉찬] 프로그래머스 - 전화번호 목록

해시/전화번호 목록.js
phone_book에 있는 모든 원소를 객체에 저장하고 하나씩 검사하여 접두어가 객체에 있는지 검사한다.
```
function solution(phone_book) {
const phoneDict = {};
phone_book.forEach((phoneNumber) => {
phoneDict[phoneNumber] = true;
});
for (const phoneNumber of phone_book) {
for (let i = 1; i < phoneNumber.length; i++) {
const curStr = phoneNumber.slice(0, i);
if (phoneDict[curStr]) return false;
}
}
return true;
}
```
=> [심민보] 전화번호

해시/전화번호 목록.js
```javascript
/테스트는 통과 했으나 효율성 테스트에서 일부 실패
function solution(phone_book) {
for (let i = 0; i < phone_book.length; i++) {
for (let j = 0; j < phone_book.length; j++) {
if (i !== j && phone_book[j].startsWith(phone_book[i])) {
return false;
}
}
}
return true;
}
```
시간을 줄이기 위해 미리 정렬을 하고 검사
```javascript
function solution(phone_book) {
phone_book.sort();
for (let i = 0; i < phone_book.length; i++) {
for (let j = 0; j < phone_book.length; j++) {
if (i !== j && phone_book[j].startsWith(phone_book[i])) {
return false;
}
}
}
return true;
}
function solution(phone_book) {
//정렬
phone_book.sort();
//특정 문자열로 시작하는지 검사
for (let i = 0; i < phone_book.length - 1; i++) {
if (phone_book[i + 1].startsWith(phone_book[i])) {
return false;
}
}
return true;
}
```
=> [김혜중] 프로그래머스 전화번호 목록

Heap/프로그래머스_더맵게.js
```js
function solution(scoville, K) {
var answer = 0;
// 오름차순 정렬
scoville.sort((a, b) => a - b);
// 모든 음식의 스코빌 지수를 K 이상으로 만들 수 없는 경우 -1 리턴
for (let i = 0; scoville[0] < K; i++) {
if (scoville.length === 1 && scoville[o] < K) {
return -1;
}
const mixScoville = scoville[0] + scoville[1] * 2;
// 섞은 음식 배열에서 제거
scoville.splice(0, 2);
// 배열에 추가
scoville.push(mixScoville);
// 섞은 횟수 추가
answer++;
// 배열 다시 정렬
scoville.sort((a, b) => a - b);
}
return answer;
}
```
=> [김혜중]프로그래머스 더 맵게

@프로그래머스/Lv. 0/flag에 따라 다른 값 반환하기.js, @프로그래머스/Lv. 0/n 번째 원소까지.js, @프로그래머스/Lv. 0/n의 배수 고르기.js, @프로그래머스/Lv. 0/n의 배수.js, @프로그래머스/Lv. 0/공배수.js, @프로그래머스/Lv. 0/문자 반복 출력하기.js, @프로그래머스/Lv. 0/문자열 붙여서 출력하기.js, @프로그래머스/Lv. 0/문자열로 변환.js, @프로그래머스/Lv. 0/문자열의 앞의 n글자.js, @프로그래머스/Lv. 0/소문자로 바꾸기.js, @프로그래머스/Lv. 0/숨어있는 숫자의 덧셈 (1).js, @프로그래머스/Lv. 0/옷가게 할인 받기.js, @프로그래머스/Lv. 0/원소들의 곱과 합.js, @프로그래머스/Lv. 0/정수 부분.js, @프로그래머스/Lv. 0/정수 찾기.js, @프로그래머스/Lv. 0/제곱수 판별하기.js, @프로그래머스/Lv. 0/짝수는 싫어요.js, @프로그래머스/Lv. 0/홀짝 구분하기.js
```js
// https://school.programmers.co.kr/learn/courses/30/lessons/181946
// 2024-03-15
// 성공
const readline = require('readline');
const rl = readline.createInterface({
input: process.stdin,
output: process.stdout,
});
let input = [];
rl.on('line', function (line) {
input = line.split(' ');
}).on('close', function () {
str1 = input[0];
str2 = input[1];
console.log(str1 + str2);
});
```
=> [정봉찬] Lv. 0 정복 - 2~3 페이지

프로그래머스 Lv0/모음 제거.js
- 0 떼기
```
function solution(n_str) {
var answer = "";
for (let i = 0; i < n_str.length; i++) {
if (n_str[i] == 0) {
continue;
} else {
answer = n_str.slice(i);
break;
}
}
return answer;
}
```
다른 사람 풀이
```
const solution = (str) => String(Number(str))
```
- 가까운 1 찾기
```
function solution(arr, idx) {
var answer = 0;
let spl = arr.splice(idx);
if (spl.includes(1)) {
answer = arr.length + spl.indexOf(1);
} else {
answer = -1;
}
return answer;
}
```
다른 사람들 풀이가 궁금합니다.
=> [심민보] 프로그래머스 Lv 0 ( 4.5 page ~ 6 page)

@프로그래머스/Lv. 0/n 번째 원소부터.js, @프로그래머스/Lv. 0/n개 간격의 원소들.js, @프로그래머스/Lv. 0/n보다 커질 때까지 더하기.js, @프로그래머스/Lv. 0/rny_string.js, @프로그래머스/Lv. 0/공백으로 구분하기 1.js, @프로그래머스/Lv. 0/길이에 따른 연산.js, @프로그래머스/Lv. 0/대문자로 바꾸기.js, @프로그래머스/Lv. 0/두 수의 연산값 비교하기.js, @프로그래머스/Lv. 0/뒤에서 5등 위로.js, @프로그래머스/Lv. 0/뒤에서 5등까지.js, @프로그래머스/Lv. 0/마지막 두 원소.js, @프로그래머스/Lv. 0/문자열 곱하기.js, @프로그래머스/Lv. 0/문자열 정수의 합.js, @프로그래머스/Lv. 0/문자열을 정수로 변환하기.js, @프로그래머스/Lv. 0/문자열의 뒤의 n글자.js, @프로그래머스/Lv. 0/배열의 길이에 따라 다른 연산하기.js, @프로그래머스/Lv. 0/배열의 원소만큼 추가하기.js, @프로그래머스/Lv. 0/부분 문자열.js, @프로그래머스/Lv. 0/부분 문자열인지 확인하기.js, @프로그래머스/Lv. 0/이어 붙인 수.js, @프로그래머스/Lv. 0/조건에 맞게 수열 변환하기 1.js, @프로그래머스/Lv. 0/조건에 맞게 수열 변환하기 3.js, @프로그래머스/Lv. 0/첫 번째로 나오는 음수.js, @프로그래머스/Lv. 0/카운트 다운.js, @프로그래머스/Lv. 0/카운트 업.js
```js
// https://school.programmers.co.kr/learn/courses/30/lessons/181927
// 2024-03-18
// 성공
function solution(num_list) {
var answer = [];
answer = [...num_list];
const length = num_list.length;
if (num_list[length - 1] > num_list[length - 2]) {
answer.push(num_list[length - 1] - num_list[length - 2]);
} else {
answer.push(num_list[length - 1] * 2);
}
return answer;
}
// 2024-03-18
// 성공
function solution(num_list) {
var answer = [];
const [a, b] = num_list.slice(-2);
answer = [...num_list, b > a ? b - a : b * 2];
return answer;
}
```
```js
// https://school.programmers.co.kr/learn/courses/30/lessons/181861
// 2024-03-19
// 성공
function solution(arr) {
var answer = [];
for (let i = 0; i < arr.length; i++) {
for (let j = 0; j < arr[i]; j++) {
answer.push(arr[i]);
}
}
return answer;
}
// …
```
=> [정봉찬] Lv. 0 정복 - 4페이지

프로그래머스/0단계/2의영역.js, 프로그래머스/0단계/7의_개수.js, 프로그래머스/0단계/qrcode.js, 프로그래머스/0단계/공던지기.js, 프로그래머스/0단계/리스트자리그.js, 프로그래머스/0단계/문자 개수 세기.js, 프로그래머스/0단계/문자열_묶기.js, 프로그래머스/0단계/문자열_반복해서출력하기.js, 프로그래머스/0단계/배열_만들기4.js, 프로그래머스/0단계/배열의길이를_2의거듭제곱으로_만들기.js, 프로그래머스/0단계/세개의_구분자.js, 프로그래머스/0단계/소인수분해.js, 프로그래머스/0단계/수열과_구간쿼리4.js, 프로그래머스/0단계/이진수더하기.js, 프로그래머스/0단계/잘라서_배열로_저장하기.js, 프로그래머스/0단계/조건에맞게_수열변환하기2.js, 프로그래머스/0단계/커피심부름.js, 프로그래머스/0단계/컨트롤_제로.js, 프로그래머스/0단계/특수문자_출력하기.js, 프로그래머스/0단계/한번만_등장한문자.js
[문자개수세기](https://school.programmers.co.kr/learn/courses/30/lessons/181902)
```js
function solution(my_string) {
// 알파벳 대소문자 배열 정의
const upperCaseLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const lowerCaseLetters = "abcdefghijklmnopqrstuvwxyz";
// 알파벳 빈도를 저장할 배열 초기화
const  answer = new Array(52).fill(0);
// 주어진 문자열을 순회하며 각 문자의 빈도 계산
for (const char of my_string) {
let index;
// 대문자인 경우
if (upperCaseLetters.includes(char)) {
index = upperCaseLetters.indexOf(char);
answer[index]++;
}
// 소문자인 경우
else if (lowerCaseLetters.includes(char)) {
index = 26 + lowerCaseLetters.indexOf(char); // 소문자는 26부터 시작
answer[index]++;
}
}
return answer;
}
```
기존에 이런식으로 풀었는데 아래 메소드로 쉽게 풀수 있네요!
```js
function solution(my_string) {
// 알파벳 대소문자에 대한 빈도를 저장할 배열 초기화
const answer = new Array(52).fill(0);
// 주어진 문자열을 순회하며 각 …
```
=> [김혜중] 프로그래머스 0단계 9페이지

@프로그래머스/Lv. 0/2의 영역.js, @프로그래머스/Lv. 0/7의 개수.js, @프로그래머스/Lv. 0/qr code.js, @프로그래머스/Lv. 0/공 던지기.js, @프로그래머스/Lv. 0/구슬을 나누는 경우의 수.js, @프로그래머스/Lv. 0/두 수의 합_.js, @프로그래머스/Lv. 0/리스트 자르기.js, @프로그래머스/Lv. 0/문자 개수 세기.js, @프로그래머스/Lv. 0/문자열 계산하기.js, @프로그래머스/Lv. 0/문자열 묶기.js, @프로그래머스/Lv. 0/문자열 반복해서 출력하기.js, @프로그래머스/Lv. 0/문자열 여러 번 뒤집기.js, @프로그래머스/Lv. 0/배열 만들기4.js, @프로그래머스/Lv. 0/배열 만들기6.js, @프로그래머스/Lv. 0/배열의 길이를 2의 거듭제곱으로 만들기.js, @프로그래머스/Lv. 0/삼각형의 완성조건 (2).js, @프로그래머스/Lv. 0/세 개의 구분자.js, @프로그래머스/Lv. 0/소인수분해.js, @프로그래머스/Lv. 0/수열과 구간 쿼리 4.js, @프로그래머스/Lv. 0/영어가 싫어요.js, @프로그래머스/Lv. 0/왼쪽 오른쪽.js, @프로그래머스/Lv. 0/이진수 더하기.js, @프로그래머스/Lv. 0/잘라서 배열로 저장하기.js, @프로그래머스/Lv. 0/조건 문자열.js, @프로그래머스/Lv. 0/조건에 맞게 수열 변환하기 2.js, @프로그래머스/Lv. 0/커피 심부름.js, @프로그래머스/Lv. 0/컨트롤 제트.js, @프로그래머스/Lv. 0/특수문자 출력하기.js, @프로그래머스/Lv. 0/한 번만 등장한 문자.js
=> [정봉찬] Lv. 0 정복 - 9페이지

@프로그래머스/Lv. 0/a와 b 출력하기.js, @프로그래머스/Lv. 0/구슬을 나누는 경우의 수.js, @프로그래머스/Lv. 0/그림 확대.js, @프로그래머스/Lv. 0/대소문자 바꿔서 출력하기.js, @프로그래머스/Lv. 0/등수 매기기.js, @프로그래머스/Lv. 0/로그인 성공.js, @프로그래머스/Lv. 0/무작위로 K개의 수 뽑기.js, @프로그래머스/Lv. 0/문자열 겹쳐쓰기.js, @프로그래머스/Lv. 0/문자열 밀기.js, @프로그래머스/Lv. 0/수열과 구간 쿼리 2.js, @프로그래머스/Lv. 0/외계어 사전.js, @프로그래머스/Lv. 0/저주의 숫자 3.js, @프로그래머스/Lv. 0/전국 대회 선발 고사.js, @프로그래머스/Lv. 0/정사각형으로 만들기.js, @프로그래머스/Lv. 0/종이 자르기.js, @프로그래머스/Lv. 0/직사각형 넓이 구하기.js, @프로그래머스/Lv. 0/치킨 쿠폰.js, @프로그래머스/Lv. 0/캐릭터의 좌표.js, @프로그래머스/Lv. 0/특이한 정렬.js
=> [정봉찬] Lv. 0 정복 - 10페이지 15문제
